### ISSUE TITLE
submission receipt with EGA accessions

### ISSUE THREAD

**Issue by lheisler** [icgc-dcc/egasub#66]
After submission, there is a message indicating success both on the terminal and in the logs.  But the accessions that are generated from the submission are not returned.

This is a feature of the REST submission system at EGA.

One can query for the accessions through the api, but there is a delay before this is available.  It would be good to report back the accession that was generated so it is available immediately

**Comment by lheisler** [comment]
Looking at the logs under 
{workspace}/.log'

I do see the accession that is generated is indicated (in my case, for Analysis object, and EGAZ accession).

It would still be better that this information was provided in a receipt of some sort, as opposed to a log file in a hidden folder

**Comment by junjun-zhang** [comment]
This is addressed in #68 as far as recording EGA Accession ID is concerned. Will later make this information more accessible via `egasub status` or `egasub report` command.

**Comment by junjun-zhang** [comment]
Upon successful submission, relevant EGA accession IDs are kept in `.status/*.log` TSV files (last row). Closing this feature request.
